#!/bin/sh
D="$(dirname "$(realpath "${0}")")"
export PYTHONPATH="$D/pym:${PYTHONPATH}"
exec python3 -c "import sys
from bob.scripts import hashEngine
sys.argv[0] = '${0##*/}'
sys.exit(hashEngine())" "$@"
