#!/usr/bin/env python3

import os
import sys

scr_path = os.path.dirname(os.path.realpath(__file__))
pym_path = os.path.join(scr_path, 'pym')
sys.path.insert(0, pym_path)

from bob.scripts import hashEngine

sys.argv[0] = os.path.basename(sys.argv[0])
sys.exit(hashEngine())
